Devise
cquiro/librarium pull request #2
Opened 2017-02-10 19:49 UTC by cquiro

# Summary

* Installed devise and created devise user.
* Installed and configured simple_token_authentication gem.
* Created endpoints for user registration and sign_in (endpoints were tested using postman).
* Added the first RSpec tests (using FactoryGirl and Faker) for user model, sessions_controller and registration_controller.

# Trello Cards

https://trello.com/c/Qub6q4mB/21-instalar-y-configurar-devise
https://trello.com/c/a3VmsFd6/23-crear-tests-con-rspec-de-modelos-y-controllers

2017-02-10 21:51 UTC, valentina91p requested changes

2017-02-10 21:51 UTC, valentina91p commented on Gemfile.lock
> +GEM
add this file to the list of ignore files

2017-02-10 21:51 UTC, valentina91p commented on app/controllers/users/registrations_controller.rb
> +        render json: resource, status: 201
use :created instead of 201

2017-02-10 21:51 UTC, valentina91p commented on app/controllers/users/sessions_controller.rb
> +      user_email = params[:session][:email]
create strong parameters method to handle this http://edgeapi.rubyonrails.org/classes/ActionController/StrongParameters.html

2017-02-10 21:51 UTC, valentina91p commented on app/controllers/users/sessions_controller.rb
> +      user = user_email.present? && User.find_by(email: user_email)
just query the user, don't validate email presence

2017-02-10 21:51 UTC, valentina91p commented on app/controllers/users/sessions_controller.rb
> +        render json: { errors: 'Invalid email or password' }, status: 422
return :not_found if user not found with email, return :unauthorized if password is not valid

2017-02-10 21:51 UTC, valentina91p commented on app/controllers/users/sessions_controller.rb
> +    # DELETE /resource/sign_out
Delete all comments in files

2017-02-10 21:51 UTC, valentina91p commented on app/models/application_record.rb
> +class ApplicationRecord < ActiveRecord::Base # :nodoc:
This class shouldn't exist anymore

2017-02-10 21:51 UTC, valentina91p commented on app/models/user.rb
> +  validates :name, presence: true
email is also mandatory

2017-02-10 21:51 UTC, valentina91p commented on app/views/devise/confirmations/new.html.erb
> +<h2>Resend confirmation instructions</h2>
Delete all these views, they will not be use

2017-02-10 21:51 UTC, valentina91p commented on circle.yml
> +      - devise
why are you changing this file? once created and configure appropiately, that's it, no more changes

2017-02-10 21:51 UTC, valentina91p commented on db/migrate/20170207184733_remove_email_from_users.rb
> +    remove_column :users, :email, :string
Why are you removing this column?

2017-02-10 21:51 UTC, valentina91p commented on spec/controllers/users/sessions_controller_spec.rb
> +      @user = FactoryGirl.create :user
let(:user) { create(:user) }, after opening the spec declaration 
https://www.relishapp.com/rspec/rspec-core/v/2-5/docs/helper-methods/let-and-let

2017-02-10 21:51 UTC, valentina91p commented on spec/controllers/users/sessions_controller_spec.rb
> +      @request.env["devise.mapping"] = Devise.mappings[:user]
why are you doing this?

2017-02-10 21:51 UTC, valentina91p commented on spec/controllers/users/sessions_controller_spec.rb
> +        post :create, params: { session: credentials }
why params? just use session: credentials

2017-02-10 21:51 UTC, valentina91p commented on spec/controllers/users/sessions_controller_spec.rb
> +        response_token = JSON.parse(response.body)["authentication_token"]
replace this with let(:response_token) { JSON.parse(response.body)["authentication_token"] } on top

2017-02-10 21:51 UTC, valentina91p commented on spec/controllers/users/sessions_controller_spec.rb
> +      @user = FactoryGirl.create :user
Add this   config.include FactoryGirl::Syntax::Methods to your spec_helper method inside Rspec.configure blog so you can just use the build and create methods directly

2017-02-10 21:51 UTC, valentina91p commented on spec/models/user_spec.rb
> +  before { @user = FactoryGirl.build(:user) }
use let instead of a global variable

2017-02-11 03:37 UTC, cquiro commented on circle.yml
> +      - devise
I got rid of those lines and won't be changing it anymore.

2017-02-11 03:37 UTC, cquiro commented on db/migrate/20170207184733_remove_email_from_users.rb
> +    remove_column :users, :email, :string
I removed it to avoid modifying Devise's migration. When I added Devise to User it inserted back this column.

2017-02-11 03:38 UTC, cquiro commented on spec/controllers/users/sessions_controller_spec.rb
> +      @request.env["devise.mapping"] = Devise.mappings[:user]
Without that line the tests don't pass and I get a tip on the command line advising me to use it. I read in Devise's GitHub page that while testing their controllers it is necessary to "tell Devise which mapping should be used before a request": https://github.com/plataformatec/devise#controller-tests

2017-02-11 03:39 UTC, cquiro commented on spec/controllers/users/sessions_controller_spec.rb
> +        post :create, params: { session: credentials }
@valentina91p I have tried that, but the test fails with the following message: 

`Failure/Error: params.require(:session).permit(:email, :password)
     ActionController::ParameterMissing:
       param is missing or the value is empty: session`

Using params was the only way I found to make the tests  work. The endpoint works fine using just the session when I test it with postman, but in RSpec I had to use params.

2017-02-13 12:53 UTC, valentina91p approved these changes

2017-02-13 12:53 UTC, valentina91p commented on app/controllers/users/sessions_controller.rb
> +        render json: { errors: 'User not found' }, status: :not_found
There's no need to return a message, that's what the not_found code signifies

2017-02-13 12:53 UTC, valentina91p commented on app/controllers/users/sessions_controller.rb
> +        render json: { errors: 'Invalid password' }, status: :unauthorized
There's no need to return a message, that's what unauthorized signifies

2017-02-13 12:53 UTC, valentina91p commented on db/migrate/20170207184733_remove_email_from_users.rb
> +    remove_column :users, :email, :string
ok

2017-02-13 13:56 UTC, merged